---
title: "CorticalArea"
output: html_document
date: "2024-11-17"
---

```{r}
library(tidyverse)
library(readxl)
library(ggplot2)

count_ca_H3 <- read.csv("H3ca_histogram.csv")
count_ca_H3 <- count_ca_H3[,-1]
count_ca_H3$H3_cluster <- paste(count_ca_H3$H1_cluster, count_ca_H3$H2_cluster, count_ca_H3$shc_result, sep = "-")

count_ca_H3$region <- gsub("BA17", "BA18", count_ca_H3$region)
count_ca_H3$region <- gsub("BA18_VMSC02901", "BA17", count_ca_H3$region)
count_ca_H3$region <- factor(count_ca_H3$region, levels = c("BA9", "BA4", "BA123", "BA40", "BA40-2", "BA22", "BA18", "BA17"))
```


```{r}
region_colors <- c(
  "BA9" = "red",
  "BA4" = "yellow",
  "BA123" = "brown",
  "BA40" = "cyan",
  "BA40-2" = "cyan",
  "BA22" = "orange",
  "BA18" = "green", 
  "BA17" = "magenta"
  )

stacked_barplot <- ggplot(count_ca_H3, aes(fill=region, y=percent, x=H3_cluster)) + 
  geom_bar(position="fill", stat="identity") +
  scale_fill_manual(values = region_colors) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5),
        axis.title.y = element_blank(),
        plot.margin = unit(c(1, 1, 1, 5), "cm"),
        plot.title.position = "plot",
        plot.title = element_text(hjust = 0.4),
        legend.position = "right"
        ) 
print(stacked_barplot)
```

```{r}
# Saving the plot
ggsave("GW34-2 Cortical Area Prop.pdf", stacked_barplot, width = 10, height = 3.8, units = "in")
```

