library(anndata)
library(stringr)
library(Matrix)
library(MASS)
library(reticulate)
library(Seurat)
library(dplyr)
library(splitstackshape)
library(ggplot2)
library(reshape2)
library(cowplot)

## results are based on files generated by "fig4GH_data_prep_cluster.ipynb" and "fig4F_gene_highvar.ipynb"

use_python("/usr/local/bin/python3.10")
setwd("~/Desktop/RA/Xuyu_Project/gene_expression")
align_legend <- function(p, hjust = 0.5) {
  # extract legend
  g <- cowplot::plot_to_gtable(p)
  grobs <- g$grobs
  legend_index <- which(sapply(grobs, function(x) x$name) == "guide-box")
  legend <- grobs[[legend_index]]
  
  # extract guides table
  guides_index <- which(sapply(legend$grobs, function(x) x$name) == "layout")
  
  # there can be multiple guides within one legend box  
  for (gi in guides_index) {
    guides <- legend$grobs[[gi]]
    
    # add extra column for spacing
    # guides$width[5] is the extra spacing from the end of the legend text
    # to the end of the legend title. If we instead distribute it by `hjust:(1-hjust)` on
    # both sides, we get an aligned legend
    spacing <- guides$width[5]
    guides <- gtable::gtable_add_cols(guides, hjust*spacing, 1)
    guides$widths[6] <- (1-hjust)*spacing
    title_index <- guides$layout$name == "title"
    guides$layout$l[title_index] <- 2
    
    # reconstruct guides and write back
    legend$grobs[[gi]] <- guides
  }
  
  # reconstruct legend and write back
  g$grobs[[legend_index]] <- legend
  # group_name <- group
  # pdf(paste0(paste0(path, group_name, sep = "/"), ".pdf",sep = ""))
  g
}


bubble_draw <- function(count_select, zs_select) {
  count_select$layer <- rownames(count_select)
  zs_select$layer <- rownames(zs_select)
  
  nonzero_sub_melt <- melt(count_select, id = c("layer"))
  expr_sub_melt <- melt(zs_select, id = c("layer"))
  color_map <- expr_sub_melt$value
  mid <- mean(color_map)
  
  col_min <- floor(min(zs_select[,1:(ncol(zs_select)-1)]))
  col_max <- ceiling(max(zs_select[,1:(ncol(zs_select)-1)]))
  
  x = ggplot(nonzero_sub_melt, aes(x = layer, y = variable, size = value, color = color_map)) + 
    # geom_point(aes(size = value, fill = layer), alpha = 1, shape = 21) + 
    geom_point(aes(size = value)) + 
    scale_size_continuous(limits = c(0.000001, 100), range = c(1,10), breaks = c(20, 40, 60, 80)) +
    labs( x= "", y = "", size = "Percentage of expressed cells (%)", fill = "", color = "Mean expression")  +
    theme(legend.title.align = 0.5,
          legend.text.align = 0.5,
          legend.key=element_blank(),
          axis.text.x = element_text(colour = "black", size = 10, face = "bold", angle = 90), 
          axis.text.y = element_text(colour = "black", face = "bold", size = 10), 
          legend.text = element_text(size = 8, face ="bold", colour ="black"), 
          legend.title = element_text(size = 8, face = "bold"), 
          panel.background = element_blank(),  #legend.spacing.x = unit(0.5, 'cm'),
          legend.position = "right",
          legend.box.just = "top",
          legend.direction = "vertical",
          legend.box="vertical",
          legend.justification="center"
    ) +  
    # theme_minimal() +
    # theme(legend.title.align = 0)+
    
    # scale_fill_manual(values = color_map, guide = FALSE) + 
    scale_y_discrete(limits = rev(levels(nonzero_sub_melt$variable))) +
    scale_color_gradient(low="yellow", high="blue", space ="Lab", limits = c(col_min, col_max), position = "bottom") +
    # scale_fill_viridis_c(guide = FALSE, limits = c(-0.5,1.5)) + 
    guides(colour = guide_colourbar(direction = "vertical", barheight = unit(4, "cm"), title.vjust = 4))
  return(x)
}


group_lst <- c("EN-ET-L5|6", "EN-ET-SP|L6b", "EN-IT-L2", "EN-IT-L3", "EN-IT-L4", "EN-IT-L5|6")

for (i in 1:length(group_lst)) {
  setwd("result")
  group <- group_lst[i]
  gene_zs <- read.csv(paste0(group, "_cluster_zs.csv"), row.names = 1)
  gene_nz <- read.csv(paste0(group, "_cluster_nz.csv"), row.names = 1)
  
  setwd("gene_var")
  gene_lst <- read.csv(paste0(group, ".csv"), row.names = 1)
  setwd("../../")
  
  # if (group == "EN-IT-L5|6") {
  #   width <- 18
  # } else if (group == "EN-IT-L3") {
  #   width <- 10
  # } else if (group == "EN-IT-L4") {
  #   width <- 8
  # } else {
  #   width <- 12
  # }

  gw_lst <- colnames(gene_lst)
  for (j in 1:length(gw_lst)) {
    gene_gw <- gene_lst[, j]
    zs_select <- gene_zs[, gene_gw]
    count_select <- gene_nz[, gene_gw]
    count_select <- count_select * 100
    
    zs_select <- zs_select[str_to_lower(substr(rownames(zs_select),1, 4)) == gw_lst[j], ]
    count_select <- count_select[str_to_lower(substr(rownames(count_select),1, 4)) == gw_lst[j], ]
    
    x <- bubble_draw(count_select, zs_select)
    setwd("fig_vargene")
    ggdraw(align_legend(x))
    ggsave(paste0(paste(group, gw_lst[j], sep = "_"), ".pdf",sep = ""),
           width = max(5, nrow(zs_select)), height = 6, limitsize = TRUE)
    # dev.off()
    setwd("../")
  }
}
