---
title: "CorticalArea"
output: html_document
date: "2023-12-25"
---

```{r}
library(tidyverse)
library(readxl)
library(ggplot2)

encluster <- read.csv("encluster.csv")
cortical_area <- read_excel("cortical_area.xlsx")
```

```{r}
encluster$sample_region <- paste(encluster$sample, encluster$region, sep = "-")
merged_encluster <- merge(encluster, cortical_area, by = "sample_region")
```

```{r}
merged_encluster$H3_annotation <- factor(merged_encluster$H3_annotation, levels = c("EN-ET-SP-early1", "EN-ET-SP-early2", "EN-ET-SP-early3", "EN-ET-L6-early4", "EN-ET-SP-2", "EN-ET-SP-A", "EN-ET-L5-1", "EN-ET-L6-A", "EN-ET-SP-3", "EN-ET-SP-4", "EN-ET-L6-early3", "EN-ET-SP-P2", "EN-ET-SP-1", "EN-ET-SP-5", "EN-ET-L6-early5", "EN-ET-SP-P1", "EN-ET-L6-early2", "EN-ET-SP-early4", "EN-ET-SP-early5", "EN-ET-L6-early1", "EN-ET-L5/6", "EN-ET-L6-P", "EN-ET-SP-V1T1", "EN-ET-SP-V1T2", "EN-ET-L6-V1", "EN-IT-L3/4-1", "EN-IT-L2/3-A2", "EN-IT-L3-A", "EN-IT-L4/5-1", "EN-IT-L4/5-early", "EN-IT-L2/3-A1", "EN-IT-L6-2", "EN-IT-L4-A", "EN-IT-L5-1", "EN-IT-L5/6-P", "EN-IT-L4-late", "EN-IT-L6-1", "EN-IT-L4/5-late", "EN-IT-Hip", "EN-IT-L3-late", "EN-IT-L3/4-early", "EN-IT-L3/4-T", "EN-IT-L3/4-P2", "EN-IT-L4-1", "EN-IT-L3-V1", "EN-IT-L4-V1", "EN-IT-L3/4-P", "EN-IT-L6-late", "EN-IT-L3-P", "EN-IZ-2", "EN-IZ-3", "EN-oSVZ-1", "EN-IZ-1", "EN-L2-2", "En-oSVZ-2", "EN-L2-3", "EN-L2-1", "EN-L2-4"))
```

```{r}
merged_encluster_ca_H3 <- merged_encluster %>%
  group_by(cortical_area, H3_annotation) %>%
  summarise(ca_count = n(), .groups = "drop")
write.csv(merged_encluster_ca_H3, "encluster_ca_H3.csv", row.names = FALSE)

merged_encluster_H3 <- merged_encluster %>%
  group_by(H3_annotation) %>%
  summarise(H3_count = n(), .groups = "drop")
write.csv(merged_encluster_H3, "encluster_H3.csv", row.names = FALSE)
```

```{r}
count_ca_H3 <- merge(merged_encluster_ca_H3, merged_encluster_H3, by = "H3_annotation")
count_ca_H3$percent <- count_ca_H3$ca_count / count_ca_H3$H3_count
count_ca_H3$cortical_area <- factor(count_ca_H3$cortical_area, levels = c("PFC", "PMC/M1", "Par", "Temp", "Occi"))
```

```{r}
stacked_barplot <- ggplot(count_ca_H3, aes(fill=cortical_area, y=percent, x=H3_annotation)) + 
  geom_bar(position="fill", stat="identity") +
  scale_fill_manual(values=c("red", "yellow", "cyan", "coral", "royalblue")) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5),
        axis.title.y = element_blank(),
        plot.margin = unit(c(1, 1, 1, 5), "cm"),
        plot.title.position = "plot",
        plot.title = element_text(hjust = 0.4),
        legend.position = "right"
        ) 
print(stacked_barplot)
```

```{r}
# Saving the plot
ggsave("Cortical Area Prop.pdf", stacked_barplot, width = 15, height = 3.8, units = "in")
```

