## Results are based on files generated by EDFig3B_data_prep.py
## Raw data are downloaded from Trevino, A. E. et al. doi:10.1016/j.cell.2021.07.039 (2021).

library(reticulate)
# use_python("/usr/local/bin/python3.10")
library(Seurat)
library(anndata)
library(scuttle)
library(SingleCellExperiment)
library(SummarizedExperiment)
library(celldex)
library(scRNAseq)
library(splitstackshape)
library(SingleR)
library(purrr)
library(dplyr)


adata_sc <- read_h5ad("data/adata_greenleaf.h5ad")
print(dim(adata_sc))
ref_data <- SingleCellExperiment(assays = list(counts = t(adata_sc$X)), rowData = rownames(adata_sc$var), 
                                colData = DataFrame(Type=adata_sc$obs$cell_type, row.names = rownames(adata_sc$obs)))  
ref_data <- logNormCounts(ref_data)

adata_tot <- read_h5ad("data/adata_tot.h5ad")
set.seed(1234)
ind_sample <- stratified(adata_tot$obs, group = "H2_annotation", size = 0.01, keep.rownames = T)
gw_rn <- ind_sample$rn
adata <- adata_tot[rownames(adata_tot$obs) %in% gw_rn]
print(dim(adata))
merfish_data <- SingleCellExperiment(assays = list(counts = t(adata$X)), colData = rownames(adata$obs), 
                                     rowData = rownames(adata$var))
merfish_data <- logNormCounts(merfish_data)
pred_clust <- SingleR(test = merfish_data, ref = ref_data, labels = adata_sc$obs$cell_type)
pred_clust <- data.frame(pred_clust)
pred_clust <- pred_clust[, (ncol(pred_clust)-1):ncol(pred_clust) ]
pred_clust$H2 <- adata$obs$H2_annotation
pred_clust$H3 <- adata$obs$H3_annotation

write.csv(pred_clust, "result/greenleaf_merscope.csv")



