## Results are based on files generated by "EDfig12A_data_prep.ipynb" 
library(dplyr)
library(ggplot2)
library(cowplot)

# Define gene and cluster lists
gene_lst <- c('GLRA2', 'TSHZ3', 'FAM107A', 'VAT1L', 'GABRA5', 'ATP2B4', 'NEFM', 'KLHL1', 'MLIP', 
              'NPR3', 'CYP26A1', 'FOXP1', 'SEMA3E', 'CUX2')
name_lst <- c('area', 'gw')
cluster_lst <- c("EN-ET-SP|L6b", "EN-ET-L5|6", "EN-IT-L5|6", "EN-IT-L4", "EN-IT-L3", "EN-IT-L2")

zs_dict <- list()

# Read and process data
for (cluster in cluster_lst) {
  zs <- read.csv(paste0("result/figs8/", cluster, "_zs.csv"), row.names = 1)
  zs <- zs[, colnames(zs) %in% c(gene_lst, name_lst)]
  zs_dict[[cluster]] <- zs
}

gene_dict <- list()

# Create gene data frames
for (gene in gene_lst) {
  gene_val <- c()
  gw_val <- c()
  cluster_val <- c()
  area_val <- c()
  
  for (cluster in cluster_lst) {
    gene_val <- c(gene_val, unlist(zs_dict[[cluster]][gene]))
    gw_val <- c(gw_val, unlist(zs_dict[[cluster]]['gw']) )
    area_val <- c(area_val, unlist(zs_dict[[cluster]]['area']) )
    cluster_val <- c(cluster_val, rep(cluster, nrow(zs_dict[[cluster]])))
  }
  
  gene_df <- data.frame(GW = gw_val, Area = area_val, Cluster = cluster_val, value = gene_val)
  gene_dict[[gene]] <- gene_df
}

align_legend <- function(p, hjust = 0.5) {
  # extract legend
  g <- cowplot::plot_to_gtable(p)
  grobs <- g$grobs
  legend_index <- which(sapply(grobs, function(x) x$name) == "guide-box")
  legend <- grobs[[legend_index]]
  
  # extract guides table
  guides_index <- which(sapply(legend$grobs, function(x) x$name) == "layout")
  
  # there can be multiple guides within one legend box  
  for (gi in guides_index) {
    guides <- legend$grobs[[gi]]
    
    # add extra column for spacing
    # guides$width[5] is the extra spacing from the end of the legend text
    # to the end of the legend title. If we instead distribute it by `hjust:(1-hjust)` on
    # both sides, we get an aligned legend
    spacing <- guides$width[5]
    guides <- gtable::gtable_add_cols(guides, hjust*spacing, 1)
    guides$widths[6] <- (1-hjust)*spacing
    title_index <- guides$layout$name == "title"
    guides$layout$l[title_index] <- 2
    
    # reconstruct guides and write back
    legend$grobs[[gi]] <- guides
  }
  
  # reconstruct legend and write back
  g$grobs[[legend_index]] <- legend
  # group_name <- group
  # pdf(paste0(paste0(path, group_name, sep = "/"), ".pdf",sep = ""))
  g
}

# Define color palette
col_map <- c('EN-ET-SP|L6b' = '#9500ff',
             'EN-ET-L5|6' = '#4a00ff',
             'EN-IT-L5|6' = '#0a98ef',
             'EN-IT-L4' = '#0ff008',
             'EN-IT-L3' = '#ffe000',
             'EN-IT-L2' = '#ec2814')

# Plot and save figures
for (gene in gene_lst) {
  gene_copy = gene_dict[[gene]]
  gene_copy$comb <- paste(gene_copy$Area, gene_copy$Cluster, sep="_")
  p <- ggplot(data = gene_copy, aes(x = GW, y = value, group = comb, color = as.factor(Cluster), linetype = Area)) +
    # geom_point() + 
    # geom_line(aes(linetype = factor(Area))) +
    geom_line(size = 0.6) +
    scale_linetype_manual(values = c("F"= "solid", "O"= "dashed", "P"= "dotted")) +
    scale_color_manual(values = col_map) +
    labs(y = "Scaled Expression", title = gene, color = "Group", linetype = "Area") +
    theme_linedraw() +
    theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank(),
          plot.title = element_text(hjust = 0.5),
          legend.title = element_text(size = 7, hjust = 0.5),
          legend.text = element_text(size = 6),
          # legend.justification = c(0, 1), legend.position = c(0.025,0.975),
          legend.background = element_rect(fill = "white", linetype="solid", colour ="black", linewidth = 0.2))
  # ggdraw(align_legend(p))
  ggsave(filename = paste0("figS8D/", gene, ".pdf"), plot = p, width = 5, height = 4, dpi = 400)
}

